### ISSUE TITLE
Schema File

### ISSUE THREAD

**Issue by alexsteinerde** [GraphQLSwift/GraphQL#31]
It would be great to have the ability to provide a schema file to the server and start it with the file content.
Or is this already possible just not listed in the readme?
Thanks
Alex

**Comment by alexsteinerde** [comment]
No I mean a .graphql file where I can specify the schema like in code.

**Comment by paulofaria** [comment]
how are you going to define the resolvers with a `.graphql` file?

**Comment by Hikaru755** [comment]
I don't know if this can be done in Swift in the same way, but with the Java implementation of GraphQL, you can just provide the schema file, and the library will automatically map the fields in the schema to the corresponding fields in the data model, or to appropriately named resolver functions if no fields are found: https://github.com/graphql-java/graphql-java-tools#resolvers-and-data-classes

**Comment by paulofaria** [comment]
@Hikaru755 This would be possible in Java by creating classes out of thin air? If so, Swift doesn't allow this. It's reflection/introspection/dynamic capabilities are very limited so far.

**Comment by Hikaru755** [comment]
It doesn't create classes on the fly, you still have to define classes and resolvers for the types in the schema, it's just the mapping that happens automatically. Basically, if you can get a list of methods of a specific object and call them dynamically by their name it should be possible. Let me explain by example, if we have the following Schema:
```
type Query {
    user: User
}
type User {
    name: String
}
```
In Java you have to pass a QueryResolver to the library (and also any additional resolvers you need, more on that later). If a request comes in, like this: ` query { user { name } } ` the library will look for a method on the query resolver that maps to the `user`-field (simply by being called `user()` or `getUser()`). It calls that method, takes its return value (for example an instance of a class called `User`), and checks if it has a method called `name()` or `getName()` on it. If it does, it calls that method and outputs its return value. If it doesn't, it then looks for any resolvers that can take a `User` instance and that have a method called `name` or `getName`, and calls those instead.

It just lets you define your schema in a language-agnostic way, and uses it to choose the correct resolver functions by naming convention, instead of having to verbosely build the schema in your implemenation logic and attach the resolvers to the fields manually.

**Comment by paulofaria** [comment]
Got it! Thanks for the thorough explanation. I believe it's possible to implement that feature in the way you mentioned. Currently I don't have as much time as I want to implement this. If anyone is interested I can give directions.

**Comment by paulofaria** [comment]
Also, I believe such a high level feature belongs to a higher level framework. Maybe github.com/graphqlswift/graphiti or another standalone framework.

**Comment by alexsteinerde** [comment]
That sounds logic to me and I have not found Grafphiti before. So thanks for the link. I will create an issue there and close it here.
Again thank you for the help.
